#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const {
  ensureDir,
  parseArgs,
  readJson,
  rootPath,
  runCli,
  usage,
  writeText
} = require("../ai/_utils.ts");

const FONT_FAMILY = "MeuMallIconFont";
const BASE_CLASS = "meu-iconfont";
const FONT_FILES = ["iconfont.woff2", "iconfont.woff", "iconfont.ttf"];

const help = usage("icons:sync", ["--source <downloaded-iconfont-directory>"]);

function main() {
  const args = parseArgs(process.argv.slice(2).filter((arg) => arg !== "--"), {
    required: ["source"]
  });

  const sourceDir = path.resolve(args.source);
  const sourceJsonPath = path.join(sourceDir, "iconfont.json");
  const sourceConfig = readJson(sourceJsonPath);

  if (!sourceConfig || !Array.isArray(sourceConfig.glyphs)) {
    throw new Error(`未找到有效的 iconfont.json：${sourceJsonPath}`);
  }

  const fontDir = rootPath("src/design-system/icons/font");
  ensureDir(fontDir);

  for (const fileName of FONT_FILES) {
    const sourcePath = path.join(sourceDir, fileName);
    if (!fs.existsSync(sourcePath)) {
      throw new Error(`缺少字体文件：${sourcePath}`);
    }
    fs.copyFileSync(sourcePath, path.join(fontDir, fileName));
  }

  const glyphs = normalizeGlyphs(sourceConfig.glyphs);
  writeText(rootPath("src/design-system/icons/iconfont.css"), createCss(glyphs));
  writeText(rootPath("src/design-system/icons/iconfont.generated.ts"), createGeneratedModule(sourceConfig, glyphs));

  console.log(`已同步 iconfont 项目 ${sourceConfig.id || "unknown"}，共 ${glyphs.length} 个图标。`);
}

function normalizeGlyphs(glyphs) {
  return glyphs.map((glyph) => {
    const rawClass = String(glyph.font_class || "").trim();
    const unicode = String(glyph.unicode || "").trim().toLowerCase();
    if (!rawClass || !/^[a-zA-Z0-9_-]+$/.test(rawClass)) {
      throw new Error(`非法 font_class：${rawClass || JSON.stringify(glyph)}`);
    }
    if (!/^[0-9a-f]+$/.test(unicode)) {
      throw new Error(`非法 unicode：${unicode || JSON.stringify(glyph)}`);
    }

    return {
      id: String(glyph.icon_id || ""),
      name: String(glyph.name || rawClass),
      rawClass,
      unicode,
      key: toGeneratedKey(rawClass)
    };
  });
}

function toGeneratedKey(rawClass) {
  const parts = String(rawClass)
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean);

  const fallback = "icon";
  const normalized = parts
    .map((part, index) => {
      const lower = part.toLowerCase();
      return index === 0 ? lower : `${lower.charAt(0).toUpperCase()}${lower.slice(1)}`;
    })
    .join("") || fallback;

  return /^[a-zA-Z_$]/.test(normalized) ? normalized : `${fallback}${normalized}`;
}

function createCss(glyphs) {
  const glyphRules = glyphs
    .map((glyph) => `.${BASE_CLASS}-${glyph.rawClass}::before {\n  content: "\\${glyph.unicode}";\n}`)
    .join("\n\n");

  return `@font-face {
  font-family: "${FONT_FAMILY}";
  src:
    url("./font/iconfont.woff2") format("woff2"),
    url("./font/iconfont.woff") format("woff"),
    url("./font/iconfont.ttf") format("truetype");
  font-display: block;
}

.${BASE_CLASS} {
  display: inline-block;
  font-family: "${FONT_FAMILY}" !important;
  font-style: normal;
  font-weight: normal;
  line-height: 1;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

${glyphRules}
`;
}

function createGeneratedModule(sourceConfig, glyphs) {
  const classMapEntries = buildUniqueKeyEntries(glyphs)
    .map(([key, rawClass]) => `  ${JSON.stringify(key)}: ${JSON.stringify(rawClass)}`)
    .join(",\n");
  const glyphEntries = glyphs
    .map((glyph) => {
      return `  {
    id: ${JSON.stringify(glyph.id)},
    name: ${JSON.stringify(glyph.name)},
    rawClass: ${JSON.stringify(glyph.rawClass)},
    unicode: ${JSON.stringify(glyph.unicode)}
  }`;
    })
    .join(",\n");

  return `// This file is generated by scripts/iconfont/sync-font-class.ts. Do not edit by hand.

export const iconFontProject = {
  id: ${JSON.stringify(String(sourceConfig.id || ""))},
  name: ${JSON.stringify(String(sourceConfig.name || ""))},
  fontFamily: ${JSON.stringify(FONT_FAMILY)},
  baseClass: ${JSON.stringify(BASE_CLASS)}
} as const;

export const iconFontGlyphs = [
${glyphEntries}
] as const;

export type IconFontRawClass = (typeof iconFontGlyphs)[number]["rawClass"];

export const iconFontClassMap = {
${classMapEntries}
} as const satisfies Record<string, IconFontRawClass>;

export type IconFontGeneratedName = keyof typeof iconFontClassMap;
`;
}

function buildUniqueKeyEntries(glyphs) {
  const seen = new Map();

  return glyphs.map((glyph) => {
    const baseKey = glyph.key;
    const count = seen.get(baseKey) || 0;
    seen.set(baseKey, count + 1);
    return [count === 0 ? baseKey : `${baseKey}${count + 1}`, glyph.rawClass];
  });
}

runCli(main, help);
