// This file is generated by scripts/iconfont/sync-font-class.ts. Do not edit by hand.

export const iconFontProject = {
  id: "5196034",
  name: "喵呜APP",
  fontFamily: "MeuMallIconFont",
  baseClass: "meu-iconfont"
} as const;

export const iconFontGlyphs = [
  {
    id: "47974033",
    name: "详情页跳转白",
    rawClass: "xiangqingyetiaozhuanbai",
    unicode: "e6af"
  },
  {
    id: "47974032",
    name: "详情页跳转黑",
    rawClass: "xiangqingyetiaozhuanhei",
    unicode: "e6b0"
  },
  {
    id: "47974031",
    name: "钱包",
    rawClass: "qianbao",
    unicode: "e6b1"
  },
  {
    id: "47974037",
    name: "清除",
    rawClass: "qingchu1",
    unicode: "e6ab"
  },
  {
    id: "47974036",
    name: "下拉",
    rawClass: "xiala",
    unicode: "e6ac"
  },
  {
    id: "47974035",
    name: "添加",
    rawClass: "tianjia",
    unicode: "e6ad"
  },
  {
    id: "47974034",
    name: "弹窗-关闭",
    rawClass: "danchuang-guanbi",
    unicode: "e6ae"
  },
  {
    id: "47967219",
    name: "收藏",
    rawClass: "shoucang",
    unicode: "e6aa"
  },
  {
    id: "47959132",
    name: "基本信息编辑",
    rawClass: "jibenxinxibianji",
    unicode: "e6a8"
  },
  {
    id: "47959131",
    name: "声音编辑",
    rawClass: "shengyinbianji",
    unicode: "e6a9"
  },
  {
    id: "47959133",
    name: "形象编辑",
    rawClass: "xingxiangbianji",
    unicode: "e6a7"
  },
  {
    id: "47938901",
    name: "loading",
    rawClass: "loading",
    unicode: "e6a6"
  },
  {
    id: "47929766",
    name: "切换",
    rawClass: "qiehuan",
    unicode: "e69f"
  },
  {
    id: "47929765",
    name: "预览",
    rawClass: "yulan",
    unicode: "e6a0"
  },
  {
    id: "47929763",
    name: "上传icon",
    rawClass: "shangchuanicon",
    unicode: "e6a1"
  },
  {
    id: "47929764",
    name: "分享",
    rawClass: "fenxiang",
    unicode: "e6a2"
  },
  {
    id: "47929762",
    name: "单选-已选",
    rawClass: "danxuan-yixuan",
    unicode: "e6a3"
  },
  {
    id: "47929761",
    name: "单选-未选",
    rawClass: "danxuan-weixuan",
    unicode: "e6a4"
  },
  {
    id: "47929760",
    name: "编辑",
    rawClass: "bianji",
    unicode: "e6a5"
  },
  {
    id: "47929837",
    name: "播放",
    rawClass: "bofang",
    unicode: "e69e"
  },
  {
    id: "47858149",
    name: "左",
    rawClass: "zuo",
    unicode: "e69c"
  },
  {
    id: "47858148",
    name: "右",
    rawClass: "you",
    unicode: "e69d"
  },
  {
    id: "47857123",
    name: "密码",
    rawClass: "mima",
    unicode: "e699"
  },
  {
    id: "47857122",
    name: "单选",
    rawClass: "danxuan",
    unicode: "e69a"
  },
  {
    id: "47857121",
    name: "单选-选中",
    rawClass: "danxuan-xuanzhong",
    unicode: "e69b"
  },
  {
    id: "47857127",
    name: "关闭显示",
    rawClass: "guanbixianshi",
    unicode: "e694"
  },
  {
    id: "47857128",
    name: "验证码",
    rawClass: "yanzhengma",
    unicode: "e695"
  },
  {
    id: "47857126",
    name: "手机号",
    rawClass: "shoujihao",
    unicode: "e696"
  },
  {
    id: "47857125",
    name: "清除",
    rawClass: "qingchu",
    unicode: "e697"
  },
  {
    id: "47857124",
    name: "Frame",
    rawClass: "Frame",
    unicode: "e698"
  }
] as const;

export type IconFontRawClass = (typeof iconFontGlyphs)[number]["rawClass"];

export const iconFontClassMap = {
  "xiangqingyetiaozhuanbai": "xiangqingyetiaozhuanbai",
  "xiangqingyetiaozhuanhei": "xiangqingyetiaozhuanhei",
  "qianbao": "qianbao",
  "qingchu1": "qingchu1",
  "xiala": "xiala",
  "tianjia": "tianjia",
  "danchuangGuanbi": "danchuang-guanbi",
  "shoucang": "shoucang",
  "jibenxinxibianji": "jibenxinxibianji",
  "shengyinbianji": "shengyinbianji",
  "xingxiangbianji": "xingxiangbianji",
  "loading": "loading",
  "qiehuan": "qiehuan",
  "yulan": "yulan",
  "shangchuanicon": "shangchuanicon",
  "fenxiang": "fenxiang",
  "danxuanYixuan": "danxuan-yixuan",
  "danxuanWeixuan": "danxuan-weixuan",
  "bianji": "bianji",
  "bofang": "bofang",
  "zuo": "zuo",
  "you": "you",
  "mima": "mima",
  "danxuan": "danxuan",
  "danxuanXuanzhong": "danxuan-xuanzhong",
  "guanbixianshi": "guanbixianshi",
  "yanzhengma": "yanzhengma",
  "shoujihao": "shoujihao",
  "qingchu": "qingchu",
  "frame": "Frame"
} as const satisfies Record<string, IconFontRawClass>;

export type IconFontGeneratedName = keyof typeof iconFontClassMap;
