import { assetUrl, type AssetUrlOptions } from "./asset-url";

export const localAssetPaths = {
  "shared.greenHeroBg": "/assets/shared/green-hero-bg.png",
  "common.icon.search": "/assets/common/icons/search.png",
  "common.icon.close": "/assets/common/icons/close.png",
  "common.icon.delete": "/assets/common/icons/delete.png",
  "seckill.heroBg": "/assets/seckill/seckill-hero-bg.png",
  "promotion.talentBadge.v1": "/assets/promotion/talent-badges/talent-badge-v1.png",
  "promotion.talentBadge.v2": "/assets/promotion/talent-badges/talent-badge-v2.png",
  "promotion.talentBadge.v3": "/assets/promotion/talent-badges/talent-badge-v3.png",
  "promotion.talentBadge.v4": "/assets/promotion/talent-badges/talent-badge-v4.png",
  "promotion.talentBadge.v5": "/assets/promotion/talent-badges/talent-badge-v5.png",
  "promotion.talentHeroBg.v1": "/assets/promotion/talent-badges/talent-hero-bg-v1.png",
  "promotion.talentHeroBg.v2": "/assets/promotion/talent-badges/talent-hero-bg-v2.png",
  "promotion.talentHeroBg.v3": "/assets/promotion/talent-badges/talent-hero-bg-v3.png",
  "promotion.talentHeroBg.v4": "/assets/promotion/talent-badges/talent-hero-bg-v4.png",
  "promotion.talentHeroBg.v5": "/assets/promotion/talent-badges/talent-hero-bg-v5.png",
  "promotion.talentSummaryCard.v1": "/assets/promotion/talent-badges/talent-summary-card-v1.png",
  "promotion.talentSummaryCard.v2": "/assets/promotion/talent-badges/talent-summary-card-v2.png",
  "promotion.talentSummaryCard.v3": "/assets/promotion/talent-badges/talent-summary-card-v3.png",
  "promotion.talentSummaryCard.v4": "/assets/promotion/talent-badges/talent-summary-card-v4.png",
  "promotion.talentSummaryCard.v5": "/assets/promotion/talent-badges/talent-summary-card-v5.png",
  "promotion.equityHeroBg.v1": "/assets/promotion/equity/equity-bg-v1.png",
  "promotion.equityHeroBg.v2": "/assets/promotion/equity/equity-bg-v2.png",
  "promotion.equityHeroBg.v3": "/assets/promotion/equity/equity-bg-v3.png",
  "promotion.equityHeroBg.v4": "/assets/promotion/equity/equity-bg-v4.png",
  "promotion.equityHeroBg.v5": "/assets/promotion/equity/equity-bg-v5.png",
  "promotion.equityArrow.next": "/assets/promotion/equity/equity-arrow-next.png",
  "promotion.equityArrow.prev": "/assets/promotion/equity/equity-arrow-prev.png",
  "promotion.equityIcon.money": "/assets/promotion/equity/equity-icon-money.png",
  "promotion.equityIcon.discount": "/assets/promotion/equity/equity-icon-discount.png",
  "promotion.equityIcon.cake": "/assets/promotion/equity/equity-icon-cake.png",
  "promotion.equityIcon.gift": "/assets/promotion/equity/equity-icon-gift.png",
  "promotion.equityIcon.coupon": "/assets/promotion/equity/equity-icon-coupon.png",
  "promotion.equityIcon.agent": "/assets/promotion/equity/equity-icon-agent.png",
  "promotion.equityIcon.box": "/assets/promotion/equity/equity-icon-box.png",
  "promotion.equityIcon.training": "/assets/promotion/equity/equity-icon-training.png",
  "promotion.equityIcon.ai": "/assets/promotion/equity/equity-icon-ai.png",
  "promotion.activityIcon.order": "/assets/promotion/activities/order-reward-icon.png",
  "promotion.activityIcon.pk": "/assets/promotion/activities/pk-reward-icon.png",
  "promotion.activityDetailHero.order": "/assets/promotion/activity-details/order-hero-bg.png",
  "promotion.activityDetailHero.pk": "/assets/promotion/activity-details/pk-hero-bg.png",
  "promotion.rewardRecordIcon.settled": "/assets/promotion/reward-records/settled-reward-icon.png",
  "promotion.rewardRecordIcon.pending": "/assets/promotion/reward-records/pending-reward-icon.png",
  "promotion.rewardRecordsBg": "/assets/shared/green-hero-bg.png",
  "promotion.rankingHeroBg": "/assets/shared/green-hero-bg.png",
  "promotion.rankingPodium.first": "/assets/promotion/ranking/ranking-podium-card-first.png",
  "promotion.rankingPodium.second": "/assets/promotion/ranking/ranking-podium-card-second.png",
  "promotion.rankingPodium.third": "/assets/promotion/ranking/ranking-podium-card-third.png",
  "promotion.rankingCrown.first": "/assets/promotion/ranking/ranking-crown-first.png",
  "promotion.rankingCrown.second": "/assets/promotion/ranking/ranking-crown-second.png",
  "promotion.rankingCrown.third": "/assets/promotion/ranking/ranking-crown-third.png",
  "promotion.icon.share": "/assets/promotion/icons/share.png",
  "promotion.icon.collect": "/assets/promotion/icons/collect.png",
  "home.logo": "/assets/home/logo.png",
  "home.message": "/assets/home/message.png",
  "home.banner.springPlan": "/assets/home/spring-plan-banner.png",
  "home.activity.seckillBg": "/assets/home/activity-seckill-bg.png",
  "home.activity.promotionBg": "/assets/home/activity-promotion-bg.png",
  "home.activity.seckillLabel": "/assets/home/seckill-label.png",
  "home.recommend.icon": "/assets/home/recommend-icon.png",
  "home.more": "/assets/home/more.png",
  "home.talentPriceTag": "/assets/home/talent-price-tag.png",
  "mine.hero.background": "/assets/shared/green-hero-bg.png",
  "mine.hero.role": "/assets/mine/hero-role.png",
  "mine.notification": "/assets/mine/mine-mascot.png",
  "mine.banner.springPlan": "/assets/mine/spring-plan-banner.png",
  "mine.order.pendingPayment": "/assets/mine/orders/pending-payment.png",
  "mine.order.pendingShipment": "/assets/mine/orders/pending-shipment.png",
  "mine.order.pendingReceipt": "/assets/mine/orders/pending-receipt.png",
  "mine.order.completed": "/assets/mine/orders/completed.png",
  "mine.order.refund": "/assets/mine/orders/refund.png",
  "mine.tool.footprint": "/assets/mine/tools/footprint.png",
  "mine.tool.favorites": "/assets/mine/tools/favorites.png",
  "mine.tool.address": "/assets/mine/tools/address.png",
  "mine.tool.settings": "/assets/mine/tools/settings.png",
  "mine.tool.customerService": "/assets/mine/tools/customer-service.png",
  "mine.tool.helpCenter": "/assets/mine/tools/help-center.png",
  "mine.tool.messageCenter": "/assets/mine/tools/message-center.png",
  "mine.tool.productService": "/assets/mine/tools/product-service.png"
} as const;

export type LocalAssetKey = keyof typeof localAssetPaths;

export function localAssetUrl(key: LocalAssetKey, options?: AssetUrlOptions) {
  return assetUrl(localAssetPaths[key], options);
}
